<!--
See http://developer.yahoo.com/ypatterns/pattern.php?pattern=searchpagination
-->

<?php if ($this->pageCount): ?>
<div class="paginationControl">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a  href="javascript:void(0)" ajax_url="<?php echo $this->url('paginator_ajax', array('id' => $this->character_id, 'page' => $this->previous)); ?>"  class="paginator_ajax_item" >
    < Previous
  </a> |
<?php else: ?>
  <span class="disabled">< Previous</span> |
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <a href="javascript:void(0)" ajax_url="<?php echo $this->url('paginator_ajax', array('id' => $this->character_id, 'page' => $page)); ?>"  class="paginator_ajax_item"  >
        <?php echo $page; ?>
    </a> |
  <?php else: ?>
    <?php echo $page; ?> |
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a href="javascript:void(0)" ajax_url="<?php echo $this->url('paginator_ajax', array('id' => $this->character_id, 'page' => $this->next)); ?>"  class="paginator_ajax_item" >
    Next >
  </a>
<?php else: ?>
  <span class="disabled">Next ></span>
<?php endif; ?>
</div>
<?php endif; ?>